package com.clinica.expedientes.model.enums;

public enum AccionAuditoria {
    CONSULTAR_EXPEDIENTE,
    MODIFICAR_EXPEDIENTE,
    CAMBIAR_ESTADO_EXPEDIENTE,
    REGISTRAR_ENTREVISTA,
    REGISTRAR_CONSENTIMIENTO,
    REGISTRAR_REPORTE,
    MODIFICAR_REPORTE,
    ENVIAR_REPORTE,
    APROBAR_REPORTE,
    RECHAZAR_REPORTE
}
